In [1]:
import pandas as pd
from pathlib import Path
glaciers_raw = pd.read_csv(Path("../Data/AK_2000_overall_glacier_covered_area.csv"))
glaciers_raw.head()

,RGIId,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,Zmin,...,Lmax,Status,Connect,Form,TermType,Surging,Linkages,Name,GN_area,GN_comp_ye
0,RGI60-01.00002,G213332E63404N,20090703,-9999999,-146.668,63.404,1,2,0.558,1713,...,1197,0,0,0,0,9,9,NaN,0.5922,2000
1,RGI60-01.00003,G213920E63376N,20090703,-9999999,-146.080,63.376,1,2,1.685,1609,...,2106,0,0,0,0,9,9,NaN,1.8045,2000
2,RGI60-01.00004,G213880E63381N,20090703,-9999999,-146.120,63.381,1,2,3.681,1273,...,4175,0,0,0,0,9,9,NaN,3.6765,2000
3,RGI60-01.00005,G212943E63551N,20090703,-9999999,-147.057,63.551,1,2,2.573,1494,...,2981,0,0,0,0,9,9,NaN,2.6064,2000
4,RGI60-01.00006,G213756E63571N,20090703,-9999999,-146.244,63.571,1,2,10.470,1201,...,10518,0,0,0,0,9,9,NaN,7.7220,2000

In [2]:
#glaciers only
glaciers=glaciers_raw[glaciers_raw['Form'] == 0]
#clarifying column names and converting to Imperial 
glaciers['Id'] = glaciers_raw['GLIMSId']
glaciers['Height (m)'] = glaciers_raw['Zmax'] - glaciers_raw['Zmin']
glaciers['Height (ft)'] = glaciers['Height (m)'] * 3.281
glaciers['Length (ft)'] = glaciers_raw['Lmax'] * 3.281
glaciers['Area (mi^2)'] = glaciers_raw['GN_area'] / 2.59
glaciers['Year'] = glaciers_raw['GN_comp_ye']
glaciers['Lat'] = glaciers_raw['CenLat']
glaciers['Lon'] = glaciers_raw['CenLon']
#removing excess columns and sorting by Id
glaciers=glaciers.sort_values(by=["Id", "Year"]).reset_index()
glaciers=glaciers[['Id','Year', 'Lat', 'Lon', 'Area (mi^2)', 'Height (ft)', 'Length (ft)']]
glaciers.head(25)

,Id,Year,Lat,Lon,Area (mi^2),Height (ft),Length (ft)
0,G193000E53881N,2000,53.881000,-167.000000,0.168880,2723.230,6949.158
1,G193000E53881N,2002,53.881000,-167.000000,0.124402,2723.230,6949.158
2,G193000E53881N,2004,53.881000,-167.000000,0.143861,2723.230,6949.158
3,G193000E53881N,2006,53.881000,-167.000000,0.129266,2723.230,6949.158
4,G193000E53881N,2008,53.881000,-167.000000,0.187297,2723.230,6949.158
5,G193000E53881N,2010,53.881000,-167.000000,0.226564,2723.230,6949.158
6,G193000E53881N,2012,53.881000,-167.000000,0.287375,2723.230,6949.158
7,G193000E53881N,2014,53.881000,-167.000000,0.165405,2723.230,6949.158
8,G193000E53881N,2016,53.881000,-167.000000,0.183127,2723.230,6949.158
9,G193000E53881N,2018,53.881000,-167.000000,0.157413,2723.230,6949.158
10,G193000E53881N,2020,53.881000,-167.000000,0.103552,2723.230,6949.158
11,G193008E53893N,2000,53.893000,-166.992000,0.048996,3238.347,5610.510
12,G193008E53893N,2002,53.893000,-166.992000,0.070541,3238.347,5610.510
13,G193008E53893N,2004,53.893000,-166.992000,0.024672,3238.347,5610.510
14,G193008E53893N,2006,53.893000,-166.992000,0.076100,3238.347,5610.510
15,G193008E53893N,2008,53.893000,-166.992000,0.087568,3238.347,5610.510
16,G193008E53893N,2010,53.893000,-166.992000,0.111892,3238.347,5610.510
17,G193008E53893N,2012,53.893000,-166.992000,0.128571,3238.347,5610.510
18,G193008E53893N,2014,53.893000,-166.992000,0.085830,3238.347,5610.510
19,G193008E53893N,2016,53.893000,-166.992000,0.148726,3238.347,5610.510
20,G193008E53893N,2018,53.893000,-166.992000,0.153243,3238.347,5610.510
21,G193008E53893N,2020,53.893000,-166.992000,0.085830,3238.347,5610.510
22,G193023E53891N,2000,53.891464,-166.976868,0.455560,3303.967,11040.565
23,G193023E53891N,2002,53.891464,-166.976868,0.483012,3303.967,11040.565
24,G193023E53891N,2004,53.891464,-166.976868,0.431583,3303.967,11040.565

In [3]:
weather_raw = pd.read_csv(Path("../Data/Weather_data_1940_to_2024.csv"))
weather_raw.head()

,Date,Monthly Total Precipitation (in),Monthly Average Mean Temperature (degF),Monthly Total Snowfall (in),City
0,1940-01,NaN,NaN,NaN,Juneau
1,1940-02,NaN,NaN,NaN,Juneau
2,1940-03,NaN,NaN,NaN,Juneau
3,1940-04,NaN,NaN,NaN,Juneau
4,1940-05,NaN,NaN,NaN,Juneau

In [4]:
weather=weather_raw
weather.loc[weather['City'] == 'Juneau', ['Lat', 'Lon']] = [58.3005, -134.433304]
weather.loc[weather['City'] == 'Fairbanks', ['Lat', 'Lon']] = [64.8401, -147.7200]
weather.loc[weather['City'] == 'Anchorage', ['Lat', 'Lon']] = [61.2176, -149.8997]
weather.loc[weather['City'] == 'Valdez', ['Lat', 'Lon']] = [61.1309, -146.3499]
weather['Year'] = weather['Date'].astype(str).str[:4]
weather = weather[weather['Year'].between('2000', '2020')]
weather=weather.sort_values(by=["City", "Year"]).reset_index()
weather=weather[['Lat','Lon', 'Year', 'Monthly Average Mean Temperature (degF)', 'Monthly Total Precipitation (in)', 'Monthly Total Snowfall (in)']]
grouped = weather.groupby('Year').mean()
grouped.reset_index(inplace=True)
grouped.head()

,Year,Lat,Lon,Monthly Average Mean Temperature (degF),Monthly Total Precipitation (in),Monthly Total Snowfall (in)
0,2000,61.372275,-144.600726,36.968125,3.406957,10.695238
1,2001,61.372275,-144.600726,36.612917,3.125208,13.143478
2,2002,61.372275,-144.600726,37.843958,3.704792,12.562791
3,2003,61.372275,-144.600726,37.645625,3.097500,11.686047
4,2004,61.372275,-144.600726,37.749167,3.387917,13.555556

In [5]:
grouped['Year'] = grouped['Year'].fillna(0).astype('int64')
merged=pd.merge(grouped, glaciers, on=['Year','Lat','Lon'], how='outer')
merged.head()

,Year,Lat,Lon,Monthly Average Mean Temperature (degF),Monthly Total Precipitation (in),Monthly Total Snowfall (in),Id,Area (mi^2),Height (ft),Length (ft)
0,2000,53.563,-166.900,NaN,NaN,NaN,G193100E53563N,0.092780,1240.218,3999.539
1,2000,53.567,-166.889,NaN,NaN,NaN,G193111E53567N,0.055598,1066.325,2424.659
2,2000,53.569,-166.910,NaN,NaN,NaN,G193090E53569N,0.006602,1007.267,2254.047
3,2000,53.570,-166.900,NaN,NaN,NaN,G193100E53570N,0.119189,931.804,1637.219
4,2000,53.570,-166.881,NaN,NaN,NaN,G193119E53570N,0.159498,1059.763,1748.773

In [6]:
merged.to_csv("../Data/UMLprep.csv", index=False, header=True)